version: '3'

services:
  web:
    image: nginx:alpine
    ports:
      - '127.0.0.1:80:80'
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf
      - public:/app/public
      - socket:/run/sspanel
    restart: always
    healthcheck:
      test: curl -fsS http://localhost:80/ping
      interval: 10s
      timeout: 2s
      # start_* not works until docker engine 25.0
      # https://github.com/moby/moby/issues/45897
      start_period: 10s
      start_interval: 2s
      retries: 2
    depends_on:
      app:
        condition: service_started

  app:
    image: jat001/sspanel-uim:latest
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./config/.config.php:/app/config/.config.php
      - ./config/appprofile.php:/app/config/appprofile.php
      - public:/app/public
      - storage:/app/storage
      - socket:/run/sspanel
    restart: always
    depends_on:
      cron:
        condition: service_healthy

  cron:
    image: jat001/sspanel-uim:latest
    entrypoint: /app/docker-entrypoint.sh
    environment:
      TZ: Asia/Shanghai
    env_file:
      - ./.env
    volumes:
      - ./config/.config.php:/app/config/.config.php
      - ./config/appprofile.php:/app/config/appprofile.php
      - storage:/app/storage
      - socket:/run/sspanel
    user: www-data:www-data
    healthcheck:
      test: test -f /tmp/docker-entrypoint.pid
      # test: >
      #   test -f /tmp/docker-entrypoint.pid &&
      #   pid="$(cat /tmp/docker-entrypoint.pid | xargs)" &&
      #   test -n "$pid" &&
      #   test -L "/proc/$pid/exe" &&
      #   test "$(readlink "/proc/$pid/exe")" = /usr/bin/bash
      interval: 5s
      timeout: 2s
      # start_* not works until docker engine 25.0
      # https://github.com/moby/moby/issues/45897
      start_period: 5s
      start_interval: 2s
      retries: 2
    restart: always

volumes:
  public:
  storage:
  socket:
