services:
  db:
    image: mariadb:latest
    ports:
      - target: 3306
        host_ip: 127.0.0.1
        published: 3306
        protocol: tcp
        mode: host
    environment:
      TZ: Asia/Shanghai
      MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
    volumes:
      - ./etc/mariadb.cnf:/etc/mysql/conf.d/99-default.cnf
      - ./mariadb:/var/lib/mysql
      - socket:/run/sspanel
    healthcheck:
      test: mariadb-admin ping -p"$$MARIADB_ROOT_PASSWORD"
      interval: 10s
      timeout: 2s
      start_period: 10s
      start_interval: 2s
      retries: 4
    restart: always
    depends_on:
      init:
        condition: service_completed_successfully

  cache:
    image: redis:alpine
    ports:
      - target: 6379
        host_ip: 127.0.0.1
        published: 6379
        protocol: tcp
        mode: host
    environment:
      TZ: Asia/Shanghai
      REDIS_DEFAULT_PASSWORD: $REDIS_DEFAULT_PASSWORD
    volumes:
      - ./etc/redis.conf:/usr/local/etc/redis/default.conf
      - ./redis:/data
      - socket:/run/sspanel
    healthcheck:
      test: redis-cli -a "$$REDIS_DEFAULT_PASSWORD" --no-auth-warning ping
      interval: 5s
      timeout: 2s
      start_period: 5s
      start_interval: 2s
      retries: 4
    restart: always
    command: >
      redis-server /usr/local/etc/redis/default.conf
      --user 'default' 'on' '>$REDIS_DEFAULT_PASSWORD' '~*' '&*' '+@all'
    depends_on:
      init:
        condition: service_completed_successfully

  init:
    image: busybox:latest
    volumes:
      - socket:/run/sspanel
    restart: on-failure
    command: chmod 0777 /run/sspanel

volumes:
  socket:
