version: '3'

services:
  web:
    image: nginx:alpine
    ports:
      - target: 80
        host_ip: 127.0.0.1
        published: 80
        protocol: tcp
        mode: host
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf
      - public:/app/public
      - socket:/run/sspanel
    restart: always
    healthcheck:
      test: curl -fsS http://localhost:80/ping
      interval: 5s
      timeout: 2s
      start_period: 5s
      start_interval: 2s
      retries: 4
    depends_on:
      app:
        condition: service_healthy

  app:
    image: jat001/sspanel-uim:latest
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./config/.config.php:/app/config/.config.php
      - ./config/appprofile.php:/app/config/appprofile.php
      - public:/app/public
      - storage:/app/storage
      - socket:/run/sspanel
    restart: always
    healthcheck:
      test: test -S /run/sspanel/php-fpm.sock && echo 'ok'
      interval: 5s
      timeout: 2s
      start_period: 5s
      start_interval: 2s
      retries: 4
    depends_on:
      cron:
        condition: service_healthy

  cron:
    image: jat001/sspanel-uim:latest
    entrypoint: /app/docker-cron.sh
    environment:
      TZ: Asia/Shanghai
    env_file:
      - ./.env
    volumes:
      - ./config/.config.php:/app/config/.config.php
      - ./config/appprofile.php:/app/config/appprofile.php
      - public:/app/public
      - storage:/app/storage
      - socket:/run/sspanel
    user: www-data:www-data
    healthcheck:
      test: >
        test -f /tmp/docker-cron.pid &&
        pid="$$(cat /tmp/docker-cron.pid | xargs)" &&
        test -n "$$pid" &&
        test -L "/proc/$$pid/exe" &&
        test "$$(readlink "/proc/$$pid/exe")" = /usr/bin/bash &&
        echo 'ok'
      interval: 10s
      timeout: 2s
      start_period: 10s
      start_interval: 2s
      retries: 4
    restart: always

  sub:
    image: jat001/subconverter:latest
    environment:
      TZ: Asia/Shanghai
    ports:
      - target: 25500
        host_ip: 127.0.0.1
        published: 25500
        protocol: tcp
        mode: host
    volumes:
      - ./etc/subconverter.toml:/etc/subconverter/pref.toml
    restart: always
    healthcheck:
      test: curl -fsS http://localhost:25500/version
      interval: 5s
      timeout: 2s
      start_period: 5s
      start_interval: 2s
      retries: 4

volumes:
  public:
  storage:
  socket:
